"""Disease Forecast model."""
from sqlalchemy import Column, Integer, String, Date, Numeric, DateTime
from sqlalchemy.sql import func
from app.database import Base


class DiseaseForecast(Base):
    """Disease case forecasts generated by AI models - 4 bệnh hô hấp."""
    
    __tablename__ = "disease_forecasts"
    
    id = Column(Integer, primary_key=True, index=True)
    forecast_month = Column(Date, nullable=False, index=True)  # Tháng dự báo (ngày đầu tháng)
    forecast_date = Column(Date, nullable=False, index=True)  # Ngày tạo dự báo
    
    # Thông tin bệnh
    icd_code = Column(String(20), nullable=False, index=True)  # J20, J06, J02, J01
    disease_name = Column(String(200), nullable=False, index=True)
    disease_type = Column(String(100), index=True)  # respiratory
    
    # Kết quả dự báo
    predicted_cases = Column(Integer, nullable=False)
    
    # Phân bổ theo mức độ (tính từ severity_rate)
    predicted_mild = Column(Integer)  # Số ca nhẹ
    predicted_moderate = Column(Integer)  # Số ca trung bình
    predicted_severe = Column(Integer)  # Số ca nặng
    
    # Độ tin cậy
    confidence_lower = Column(Integer)
    confidence_upper = Column(Integer)
    
    # Thông tin mô hình
    model_used = Column(String(50))  # xgboost, lstm, prophet, ensemble
    model_accuracy_mae = Column(Numeric(10, 2))
    model_accuracy_rmse = Column(Numeric(10, 2))
    model_accuracy_mape = Column(Numeric(5, 2))
    forecast_period_days = Column(Integer, default=30)
    
    # Phân loại rủi ro
    risk_level = Column(String(20))  # 'low' | 'medium' | 'high' | 'very_high'
    baseline_cases = Column(Integer)  # Ca nền (TB cùng kỳ các năm)
    weather_factor = Column(Numeric(5, 3))
    trend_factor = Column(Numeric(5, 3))
    explanation = Column(String(1000))  # Giải thích mô hình
    
    # Địa điểm
    location = Column(String(100), index=True)
    
    # Theo dõi sai số
    actual_cases = Column(Integer)
    deviation_pct = Column(Numeric(7, 2))
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(String(100))
