"""Seed data cho 4 bệnh hô hấp và 15 thuốc/vật tư."""

# 4 bệnh hô hấp
DISEASES = [
    {
        "icd_code": "J20",
        "disease_name": "Viêm phế quản cấp",
        "disease_type": "respiratory",
    },
    {
        "icd_code": "J06",
        "disease_name": "Nhiễm trùng đường hô hấp trên cấp",
        "disease_type": "respiratory",
    },
    {
        "icd_code": "J02",
        "disease_name": "Viêm họng cấp",
        "disease_type": "respiratory",
    },
    {
        "icd_code": "J01",
        "disease_name": "Viêm xoang cấp",
        "disease_type": "respiratory",
    },
]

# Tỷ lệ mức độ mặc định cho 4 bệnh
SEVERITY_RATES = [
    {
        "icd_code": "J20",
        "disease_name": "Viêm phế quản cấp",
        "mild_rate": 60.0,
        "moderate_rate": 30.0,
        "severe_rate": 10.0,
        "note": "Bệnh có thể có nhóm cần khí dung hoặc điều trị tiêm/truyền khi nặng.",
    },
    {
        "icd_code": "J06",
        "disease_name": "Nhiễm trùng đường hô hấp trên cấp",
        "mild_rate": 70.0,
        "moderate_rate": 25.0,
        "severe_rate": 5.0,
        "note": "Phần lớn là ca nhẹ, một tỷ lệ nhỏ cần kháng sinh hoặc theo dõi.",
    },
    {
        "icd_code": "J02",
        "disease_name": "Viêm họng cấp",
        "mild_rate": 75.0,
        "moderate_rate": 20.0,
        "severe_rate": 5.0,
        "note": "Bệnh thường nhẹ, tỷ lệ nặng thấp.",
    },
    {
        "icd_code": "J01",
        "disease_name": "Viêm xoang cấp",
        "mild_rate": 70.0,
        "moderate_rate": 25.0,
        "severe_rate": 5.0,
        "note": "Đa số điều trị ngoại trú, một số ca cần kháng sinh/kháng viêm.",
    },
]

# 15 thuốc/vật tư
MEDICAL_SUPPLIES = [
    {
        "supply_code": "VT001",
        "drug_code": "A2A210200000133",
        "ten_hoat_chat": "Paracetamol",
        "unit": "Viên",
        "group_name": "Thuốc hạ sốt, giảm đau",
        "category": "medicine",
        "description": "Efferalgan 500 mg, đơn vị viên; dùng làm mã đại diện Paracetamol dạng uống.",
    },
    {
        "supply_code": "VT002",
        "drug_code": "A2C816100000074",
        "ten_hoat_chat": "Natri clorid",
        "unit": "Chai",
        "group_name": "Dung dịch/dịch truyền",
        "category": "medicine",
        "description": "Natri clorid 0,9% 100 mL, đơn vị chai.",
    },
    {
        "supply_code": "VT003",
        "drug_code": "A2C715800000009",
        "ten_hoat_chat": "N-acetylcysteine",
        "unit": "Gói",
        "group_name": "Thuốc long đờm",
        "category": "medicine",
        "description": "ACC 200 mg, đơn vị gói.",
    },
    {
        "supply_code": "VT004",
        "drug_code": "A2A300000000058",
        "ten_hoat_chat": "Fexofenadin",
        "unit": "Viên",
        "group_name": "Kháng histamin",
        "category": "medicine",
        "description": "Telfast HD 180 mg, đơn vị viên.",
    },
    {
        "supply_code": "VT005",
        "drug_code": "A2A610720000036",
        "ten_hoat_chat": "Amoxicilin + acid clavulanic",
        "unit": "Viên",
        "group_name": "Kháng sinh uống",
        "category": "medicine",
        "description": "Augmentin BD 875/125 mg, đơn vị viên.",
    },
    {
        "supply_code": "VT006",
        "drug_code": "A2A610720000734",
        "ten_hoat_chat": "Ceftriaxon",
        "unit": "Lọ",
        "group_name": "Kháng sinh tiêm",
        "category": "medicine",
        "description": "Ceftriaxon 2 g, đơn vị lọ.",
    },
    {
        "supply_code": "VT007",
        "drug_code": "A2A610720000514",
        "ten_hoat_chat": "Cefoperazon + sulbactam",
        "unit": "Lọ",
        "group_name": "Kháng sinh tiêm",
        "category": "medicine",
        "description": "Sulraapix 2 g, đơn vị lọ.",
    },
    {
        "supply_code": "VT008",
        "drug_code": "A2B914100000236",
        "ten_hoat_chat": "Methylprednisolon",
        "unit": "Lọ",
        "group_name": "Kháng viêm corticosteroid",
        "category": "medicine",
        "description": "Methylprednisolone Normon Inj. 40 mg, đơn vị lọ.",
    },
    {
        "supply_code": "VT009",
        "drug_code": "A2C715700000122",
        "ten_hoat_chat": "Salbutamol + ipratropium",
        "unit": "Lọ",
        "group_name": "Thuốc khí dung/giãn phế quản",
        "category": "medicine",
        "description": "Combivent 2,5 + 0,5 mg/2,5 mL, đơn vị lọ.",
    },
    {
        "supply_code": "VT010",
        "drug_code": "A2C715700000102",
        "ten_hoat_chat": "Budesonid",
        "unit": "Ống",
        "group_name": "Corticoid khí dung",
        "category": "medicine",
        "description": "Pulmicort Respules 1 mg/2 mL, đơn vị ống.",
    },
    {
        "supply_code": "VT011",
        "drug_code": "A2B813400000061",
        "ten_hoat_chat": "Esomeprazol",
        "unit": "Viên",
        "group_name": "Thuốc hỗ trợ đường tiêu hóa",
        "category": "medicine",
        "description": "Stadnex 40 CAP, đơn vị viên.",
    },
    {
        "supply_code": "VT012",
        "drug_code": "A2C900000000138",
        "ten_hoat_chat": "Vitamin C",
        "unit": "Viên",
        "group_name": "Thuốc hỗ trợ",
        "category": "medicine",
        "description": "Vitamin C Stella 1 g, đơn vị viên.",
    },
    {
        "supply_code": "VT013",
        "drug_code": "B2G324024800053",
        "ten_hoat_chat": "Bơm tiêm (syringe) dùng một lần các loại, các cỡ",
        "unit": "Cái",
        "group_name": "Vật tư y tế",
        "category": "medical_supply",
        "description": "Bơm tiêm 20cc 23Gx1 Vikimco, đơn vị cái.",
    },
    {
        "supply_code": "VT014",
        "drug_code": "B2G324126100020",
        "ten_hoat_chat": "Kim tiêm",
        "unit": "Cái",
        "group_name": "Vật tư y tế",
        "category": "medical_supply",
        "description": "Kim tiêm vô trùng sử dụng một lần, đơn vị cái.",
    },
    {
        "supply_code": "VT015",
        "drug_code": "B2G324428100030",
        "ten_hoat_chat": "Dây truyền dịch",
        "unit": "Cái",
        "group_name": "Vật tư y tế",
        "category": "medical_supply",
        "description": "Intrafix Primeline LL 180cm, đơn vị cái.",
    },
]

# Định mức thuốc/vật tư theo bệnh và mức độ
# Format: (icd_code, severity, supply_code, quantity_per_case)
DISEASE_SUPPLY_NORMS = [
    # J20 - Viêm phế quản cấp
    ("J20", "mild", "VT001", 6),
    ("J20", "mild", "VT003", 5),
    ("J20", "mild", "VT009", 0),
    ("J20", "mild", "VT010", 0),
    ("J20", "mild", "VT002", 0),
    ("J20", "mild", "VT005", 0),
    ("J20", "mild", "VT006", 0),
    ("J20", "mild", "VT013", 0),
    ("J20", "mild", "VT014", 0),
    ("J20", "mild", "VT015", 0),
    
    ("J20", "moderate", "VT001", 10),
    ("J20", "moderate", "VT003", 7),
    ("J20", "moderate", "VT009", 3),
    ("J20", "moderate", "VT010", 3),
    ("J20", "moderate", "VT002", 1),
    ("J20", "moderate", "VT005", 6),
    ("J20", "moderate", "VT006", 0),
    ("J20", "moderate", "VT013", 1),
    ("J20", "moderate", "VT014", 1),
    ("J20", "moderate", "VT015", 1),
    
    ("J20", "severe", "VT001", 12),
    ("J20", "severe", "VT003", 10),
    ("J20", "severe", "VT009", 5),
    ("J20", "severe", "VT010", 5),
    ("J20", "severe", "VT002", 2),
    ("J20", "severe", "VT005", 10),
    ("J20", "severe", "VT006", 2),
    ("J20", "severe", "VT013", 2),
    ("J20", "severe", "VT014", 2),
    ("J20", "severe", "VT015", 1),
    
    # J06 - Nhiễm trùng đường hô hấp trên cấp
    ("J06", "mild", "VT001", 6),
    ("J06", "mild", "VT004", 5),
    ("J06", "mild", "VT003", 3),
    ("J06", "mild", "VT012", 5),
    ("J06", "mild", "VT005", 0),
    ("J06", "mild", "VT002", 0),
    ("J06", "mild", "VT008", 0),
    ("J06", "mild", "VT013", 0),
    ("J06", "mild", "VT014", 0),
    
    ("J06", "moderate", "VT001", 10),
    ("J06", "moderate", "VT004", 7),
    ("J06", "moderate", "VT003", 5),
    ("J06", "moderate", "VT012", 7),
    ("J06", "moderate", "VT005", 6),
    ("J06", "moderate", "VT002", 1),
    ("J06", "moderate", "VT008", 0),
    ("J06", "moderate", "VT013", 1),
    ("J06", "moderate", "VT014", 1),
    
    ("J06", "severe", "VT001", 12),
    ("J06", "severe", "VT004", 7),
    ("J06", "severe", "VT003", 7),
    ("J06", "severe", "VT012", 10),
    ("J06", "severe", "VT005", 10),
    ("J06", "severe", "VT002", 2),
    ("J06", "severe", "VT008", 1),
    ("J06", "severe", "VT013", 2),
    ("J06", "severe", "VT014", 2),
    
    # J02 - Viêm họng cấp
    ("J02", "mild", "VT001", 6),
    ("J02", "mild", "VT004", 3),
    ("J02", "mild", "VT012", 5),
    ("J02", "mild", "VT005", 0),
    ("J02", "mild", "VT008", 0),
    ("J02", "mild", "VT002", 0),
    ("J02", "mild", "VT013", 0),
    ("J02", "mild", "VT014", 0),
    
    ("J02", "moderate", "VT001", 10),
    ("J02", "moderate", "VT004", 5),
    ("J02", "moderate", "VT012", 7),
    ("J02", "moderate", "VT005", 6),
    ("J02", "moderate", "VT008", 1),
    ("J02", "moderate", "VT002", 1),
    ("J02", "moderate", "VT013", 1),
    ("J02", "moderate", "VT014", 1),
    
    ("J02", "severe", "VT001", 12),
    ("J02", "severe", "VT004", 7),
    ("J02", "severe", "VT012", 10),
    ("J02", "severe", "VT005", 10),
    ("J02", "severe", "VT008", 2),
    ("J02", "severe", "VT002", 1),
    ("J02", "severe", "VT013", 2),
    ("J02", "severe", "VT014", 2),
    
    # J01 - Viêm xoang cấp
    ("J01", "mild", "VT001", 6),
    ("J01", "mild", "VT004", 5),
    ("J01", "mild", "VT003", 3),
    ("J01", "mild", "VT005", 0),
    ("J01", "mild", "VT008", 0),
    ("J01", "mild", "VT002", 1),
    ("J01", "mild", "VT013", 0),
    ("J01", "mild", "VT014", 0),
    
    ("J01", "moderate", "VT001", 10),
    ("J01", "moderate", "VT004", 7),
    ("J01", "moderate", "VT003", 5),
    ("J01", "moderate", "VT005", 6),
    ("J01", "moderate", "VT008", 1),
    ("J01", "moderate", "VT002", 1),
    ("J01", "moderate", "VT013", 1),
    ("J01", "moderate", "VT014", 1),
    
    ("J01", "severe", "VT001", 12),
    ("J01", "severe", "VT004", 10),
    ("J01", "severe", "VT003", 7),
    ("J01", "severe", "VT005", 10),
    ("J01", "severe", "VT008", 2),
    ("J01", "severe", "VT002", 2),
    ("J01", "severe", "VT013", 2),
    ("J01", "severe", "VT014", 2),
]
